POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane I",
    "email": "jane@test.com"
}



####
POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "ce4dfc50-8b74-4f05-99a0-56b21f005e10"
}


####
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "8b6c5aa4-66ef-403d-aeb1-a06156385388",
    "account_id_to": "7a21aa94-5e52-4e06-b12e-735f8711609e",
    "amount": 100
}